# Generated by Django 2.2.3 on 2019-10-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='ContributionPermission',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('permission_name', models.CharField(max_length=100, unique=True)),
			],
			options={
				'db_table': 'psp_contribution_permission',
			},
		),
		migrations.CreateModel(
			name='ContributionStatus',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('status', models.IntegerField(
					choices=[(0, 'Approved'), (1, 'Rejected'), (2, 'Declined'), (4, 'Cancelled')],
					db_column='status_id', db_index=True)),
				('when_recorded', models.DateTimeField(db_column='dt')),
			],
			options={
				'verbose_name_plural': 'Contribution Statuses',
				'db_table': 'psp_status',
			},
		),
	]
