# Generated by Django 2.2.3 on 2019-10-25 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('permission', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='contributionstatus',
			name='created_by',
			field=models.ForeignKey(default=None, null=True,
			                        on_delete=django.db.models.deletion.SET_NULL,
			                        to=settings.AUTH_USER_MODEL),
		),
	]
