# Generated by Django 2.2.3 on 2019-08-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contributionpermission',
            table='psp_contribution_permission',
        ),
    ]
