# Generated by Django 2.2.3 on 2020-07-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20200708_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuepermission',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuepermission',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
