version: "3"

services:
    proxy:
        image: traefik   # the official Traefik docker image
        container_name: pprosper_traefik
        restart: on-failure
        command: --api --docker # enables the web UI and tells Traefik to listen to docker
        ports:
            - 80:80     # the HTTP port
            - 443:443   # https Port
            - 8081:8081 # the Web UI (enabled by --api)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./proxy/traefik.toml:/etc/traefik/traefik.toml
            - ./proxy/acme.json:/acme.json

    elastic-kibana:
        tty: true
        build: ./elasticsearch
        image: prosper-elastic-kibana
        container_name: prosper_elastic-kibana
        restart: always
        links:
            - proxy:local.prosperinv.com
        environment:
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=prosper-inv
        volumes:
            - ./elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
            - ./elasticsearch/data/:/var/lib/elasticsearch/
            - ./elasticsearch/logs/:/usr/share/elasticsearch/logs/
            - ./elasticsearch/kibana.yml:/etc/kibana/kibana.yml
            - ./elasticsearch/kibana/data/:/var/lib/kibana/
            - ./elasticsearch/kibana/logs/:/var/log/kibana/
            - ./elasticsearch/logstash.conf:/etc/logstash/conf.d/logstash.conf
            - ./elasticsearch/logstash.yml:/etc/logstash/logstash.yml
            - ./elasticsearch/logstash/logs/:/usr/share/logstash/logs/
            - ./elasticsearch/nginx.conf:/etc/nginx/sites-enabled/default
            - ./elasticsearch:/opt/elastic/
        command: bash -c "./elasticsearch-setup.sh"
        ports:
            - 9200:9200
            - 9600:9600
            - 5601:5601
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        labels:
            - traefik.enable=true
            - traefik.backend=elastic-kibana
            - traefik.port=90
            - traefik.frontend.passHostHeader=true
            - traefik.frontend.rule=Host:local.prosperinv.com;PathPrefix:/kibana

    rest-api:
        build: ./
        image: prosper-rest-api
        container_name: prosper_rest-api
        volumes:
            - ./:/usr/src/app/
        environment:
            - DJANGO_SETTINGS_MODULE=prosper_investments.settings.docker
            - ENV=local
            - LOGSTASH_HOST=elastic-kibana
            - LOGSTASH_POST=9600
            - ELASTICSEARCH_URL=http://elastic-kibana:9200
            - DB_HOST=db
            - DB_NAME=prosper_investments
            - DB_USERNAME=prosper_investments
            - DB_PASSWORD=prosper_investments
            - DB_PORT=3306
            - EMAIL_HOST_USER=yosam.db@gmail.com
            - EMAIL_HOST_PASSWORD=ronald@507
            - BASE_URL=http://local.prosperinv.com/api
        links:
            - proxy:local.prosperinv.com
            - db
            - elastic-kibana
        labels:
            - traefik.enable=true
            - traefik.port=8000
            - traefik.api.backend=rest-api
            - traefik.api.frontend.passHostHeader=true
            - traefik.api.frontend.rule=Host:local.prosperinv.com;PathPrefixStrip:/api
            - traefik.static.backend=rest-api-static
            - traefik.static.frontend.rule=Host:local.prosperinv.com;PathPrefix:/admin,/media,/static
        depends_on:
            - db
        command: bash -c "pip install -r requirements.txt && bash ./docker/run.sh"

    db:
        image: mysql:5.7
        container_name: prosper_db
        command: ["--general_log=1", "--log_output=TABLE", "--explicit_defaults_for_timestamp=1"]
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=prosper_investments
            - MYSQL_DATABASE=prosper_investments
            - MYSQL_USER=prosper_investments
        ports:
            - 3307:3306
        restart: always
        volumes:
            - ./tmp-docker-vol/mysql:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot"]
            interval: 30s
            timeout: 30s
            retries: 10
