# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:59
from __future__ import unicode_literals

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import home.support.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='deposit date')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, help_text='your contribution this month', max_digits=11, verbose_name='deposit')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, help_text='charges deducted from this contribution', max_digits=11, verbose_name='penalty')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total amount contributed when charges are deducted', max_digits=11, verbose_name='actual contribution')),
                ('deposit_slip', models.FileField(blank=True, db_column='deposit slip', help_text='upload deposit slip if available.. Only .pdf files are allowed', upload_to='deposit_slips', validators=[home.support.validators.FileValidator(allowed_extensions=['pdf'], allowed_mimetypes=['application/pdf'], max_size=5242880, min_size=1)])),
            ],
            options={
                'ordering': ['-contribution_date', 'user'],
                'default_permissions': ('add', 'delete', 'modify', 'view'),
                'get_latest_by': 'contribution_date',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='Interest Rate(%) monthly')),
            ],
            options={
                'default_permissions': ('add', 'modify'),
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('project_name', models.CharField(default='', max_length=255, verbose_name='Project name')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Project start date')),
                ('project_age', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Project Age/Length (months)')),
                ('project_rating', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='please rate the project performance using the slider', max_digits=3, verbose_name='Project Performance')),
                ('project_status', models.CharField(choices=[('in_progress', 'In Progress'), ('cancelled', 'Canceled'), ('completed', 'Completed')], default='in_progress', help_text='select/update the current status of the project', max_length=255)),
                ('total_capital_invested', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Capital Invested')),
                ('amount_returned', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Amount Returned')),
                ('interest', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Interest')),
                ('loss', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Loss')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('positive_highlights', models.TextField(blank=True, verbose_name='Positive highlights')),
                ('challenges', models.TextField(blank=True, help_text='challenges/problems encountered while on this project', verbose_name='Challenges')),
                ('lessons_learnt', models.TextField(blank=True, help_text='new lessons learnt while on this project', verbose_name='Lessons learnt')),
                ('way_foward', models.TextField(blank=True, help_text='what do you conclude as a ay forward for the team/organisation', verbose_name='Way forward')),
            ],
            options={
                'ordering': ['-start_date', 'project_name'],
                'default_permissions': ('add', 'delete', 'modify', 'view'),
            },
        ),
        migrations.CreateModel(
            name='InvestmentFinancialStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='date of activity instantiation', verbose_name='Acttivity date')),
                ('particulars', models.TextField(blank=True, default='', null=True, verbose_name='particulars')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, help_text='How much was spent on this activity', max_digits=12, verbose_name='Amount Spent')),
                ('amount_returned', models.DecimalField(decimal_places=2, default=0, help_text='How much is returned after the activity', max_digits=12, verbose_name='Amount Returned')),
                ('cash_at_hand', models.DecimalField(decimal_places=2, default=0, help_text='Dry Cash currently available', max_digits=12, verbose_name='Cash at hand')),
            ],
            options={
                'default_permissions': ('add', 'delete', 'modify', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now, help_text='loan start date', verbose_name='loan date')),
                ('loan_duration', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Loan Duration(months)')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Loan Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount paid')),
                ('sur_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sur charge.')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sub total.')),
                ('loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Interest Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Outstanding Bal.')),
                ('profit_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Profits')),
                ('loan_status', models.CharField(choices=[('running', 'loan running'), ('cancelled', 'Canceled'), ('completed', 'Completed')], default='running', max_length=255)),
            ],
            options={
                'ordering': ['-loan_date', 'total_amount'],
                'default_permissions': ('add', 'delete', 'modify', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount paid.')),
                ('loan', models.ForeignKey(help_text='loan being repayed', on_delete=django.db.models.deletion.CASCADE, to='finance.Loan')),
            ],
            options={
                'default_permissions': ('add', 'delete', 'modify', 'view'),
            },
        ),
    ]
