# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monthly',
        ),
    ]
