# Generated by Django 2.2.3 on 2019-10-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='OAuthProvider',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100)),
				('client_id', models.CharField(max_length=100)),
				('client_secret', models.CharField(max_length=100)),
				('publishable_key', models.CharField(max_length=250, null=True)),
				('authorize_url', models.CharField(max_length=100)),
				('api_url', models.CharField(max_length=100)),
				('token_url', models.CharField(max_length=100)),
				('redirect_url', models.CharField(max_length=100)),
			],
			options={
				'db_table': 'psp_oauth_providers',
			},
		),
		migrations.CreateModel(
			name='VenueToken',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('oauth_token', models.TextField()),
				('refresh_token', models.TextField()),
				('created_at', models.BigIntegerField(null=True)),
				('expires_in', models.BigIntegerField(null=True)),
				('token_type', models.CharField(max_length=100, null=True)),
				('stripe_user_id', models.CharField(max_length=100, null=True)),
				('stripe_publishable_key', models.CharField(max_length=100, null=True)),
				('provider', models.ForeignKey(
					db_column='oauth_provider_id', on_delete=django.db.models.deletion.CASCADE,
					related_name='venue_tokens', to='oauth.OAuthProvider')),
			],
			options={
				'db_table': 'psp_oauth_venue_tokens',
			},
		),
	]
