# Generated by Django 2.2.3 on 2019-10-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('venue', '0001_initial'),
		('oauth', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='venuetoken',
			name='venue',
			field=models.ForeignKey(db_column='psp_venue_id',
			                        on_delete=django.db.models.deletion.CASCADE, to='venue.Venue'),
		),
	]
