# Generated by Django 2.2.3 on 2020-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_venuetoken_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthprovider',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venuetoken',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venuetoken',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
