# Generated by Django 2.2.3 on 2019-08-12 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('venue', '0002_auto_20190811_1537'),
	]

	operations = [
		migrations.CreateModel(
			name='UserType',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=50)),
				('venues', models.ManyToManyField(
					blank=True, db_constraint=False, related_name='user_types', to='venue.Venue')),
			],
			options={
				'db_table': 'psp_users_type',
			},
		),
		migrations.CreateModel(
			name='UsersAdminVenues',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('user', models.ForeignKey(
					db_column='psp_user_id', on_delete=django.db.models.deletion.CASCADE,
					to=settings.AUTH_USER_MODEL)),
				('venue', models.ForeignKey(
					db_column='psp_venue_id', on_delete=django.db.models.deletion.CASCADE,
					to='venue.Venue')),
			],
			options={
				'verbose_name_plural': 'Admin Venues',
				'db_table': 'psp_users_admin_venues',
			},
		),
		migrations.AddField(
			model_name='user',
			name='admin_venues',
			field=models.ManyToManyField(
				related_name='admin_users', through='venue.UsersAdminVenues', to='venue.Venue'),
		),
		migrations.AddField(
			model_name='user',
			name='user_type',
			field=models.ForeignKey(
				blank=True, db_column='psp_users_type_id', null=True,
				on_delete=django.db.models.deletion.SET_NULL, to='venue.UserType'),
		),
	]
