# Generated by Django 2.2.3 on 2019-08-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'psp_languages',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key used in the front-end, e.g. `INDEX_title`', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional explanation of the key')),
            ],
            options={
                'db_table': 'psp_terms',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminology.Language')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminology.Term')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.Venue')),
            ],
            options={
                'db_table': 'psp_translations',
                'ordering': ('term__key', 'language__code'),
                'unique_together': {('venue', 'term', 'language')},
            },
        ),
    ]
