# Generated by Django 2.2.3 on 2019-10-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Language',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('code', models.CharField(max_length=10, unique=True)),
				('name', models.CharField(max_length=100, unique=True)),
				('active', models.BooleanField(default=True)),
			],
			options={
				'db_table': 'psp_languages',
			},
		),
		migrations.CreateModel(
			name='Term',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('key', models.CharField(
					help_text='The key used in the front-end, e.g. `INDEX_title`', max_length=150)),
				('description', models.TextField(
					blank=True, help_text='Optional explanation of the key')),
			],
			options={
				'db_table': 'psp_terms',
				'ordering': ('key',),
			},
		),
		migrations.CreateModel(
			name='Translation',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('value', models.TextField()),
				('language', models.ForeignKey(
					on_delete=django.db.models.deletion.CASCADE, to='terminology.Language')),
				('term', models.ForeignKey(
					on_delete=django.db.models.deletion.CASCADE, to='terminology.Term')),
			],
			options={
				'db_table': 'psp_translations',
				'ordering': ('term__key', 'language__code'),
			},
		),
	]
