# Generated by Django 2.2.3 on 2019-10-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('venue', '0001_initial'),
		('terminology', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='translation',
			name='venue',
			field=models.ForeignKey(blank=True, null=True,
			                        on_delete=django.db.models.deletion.SET_NULL, to='venue.Venue'),
		),
		migrations.AlterUniqueTogether(
			name='translation',
			unique_together={('venue', 'term', 'language')},
		),
	]
