# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdetails',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Start date'),
        ),
    ]
