# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clubdetails_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubdetails',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Start date'),
        ),
    ]
