# Generated by Django 2.2.3 on 2019-12-11 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import prosper_investments.apps.account.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(default=prosper_investments.apps.account.utils.generate_account_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('deleted', 'Exited / deleted'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('initial_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.Venue')),
            ],
            options={
                'db_table': 'psp_account',
            },
        ),
        migrations.CreateModel(
            name='AccountTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('previous_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('current_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit'), ('transfer', 'Transfer')], default='deposit', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teller', to=settings.AUTH_USER_MODEL)),
                ('transfer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to_account', to='account.Account')),
            ],
            options={
                'db_table': 'psp_account_transactions',
            },
        ),
    ]
