# Generated by Django 2.2.3 on 2019-12-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191211_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('deleted', 'Exited / deleted'), ('pending', 'Pending Approval')], default='pending', max_length=20),
        ),
    ]
