# Generated by Django 2.2.3 on 2020-03-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191211_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('deleted', 'deleted'), ('pending', 'Pending Approval'), ('deactivated', 'Deactivated')], default='pending', max_length=20),
        ),
    ]
