# Generated by Django 2.2.3 on 2019-10-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('permission', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='ApiKey',
			fields=[
				('created_date', models.DateTimeField(auto_now=True)),
				('modified_date', models.DateTimeField(auto_now=True)),
				('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
				('created', models.DateTimeField(auto_now_add=True)),
			],
			options={
				'db_table': 'psp_api_key',
			},
		),
		migrations.CreateModel(
			name='DashboardSection',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('route_name', models.CharField(max_length=100)),
				('name', models.CharField(max_length=100, unique=True)),
				('is_visible_to_all', models.BooleanField(default=False)),
			],
			options={
				'db_table': 'psp_dashboard_sections',
			},
		),
		migrations.CreateModel(
			name='TemporaryToken',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True)),
				('modified_date', models.DateTimeField(auto_now=True)),
				('key', models.CharField(max_length=255)),
				('additional_info', models.TextField(blank=True, null=True)),
				('created', models.DateTimeField(auto_now=True)),
				('service', models.CharField(max_length=255)),
			],
			options={
				'db_table': 'psp_temporary_token',
			},
		),
		migrations.CreateModel(
			name='VenueViewerType',
			fields=[
				('id', models.AutoField(
					auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_date', models.DateTimeField(auto_now=True)),
				('modified_date', models.DateTimeField(auto_now=True)),
				('name', models.CharField(max_length=100)),
				('permissions', models.ManyToManyField(to='permission.ContributionPermission')),
				(
					'sections',
					models.ManyToManyField(related_name='viewer_types',
					                       to='user.DashboardSection')),
			],
			options={
				'db_table': 'psp_venue_viewer_type',
			},
		),
	]
