# Generated by Django 2.2.3 on 2019-10-25 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('user', '0001_initial'),
		('venue', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name='venueviewertype',
			name='users',
			field=models.ManyToManyField(related_name='viewer_types', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='venueviewertype',
			name='venue',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.Venue'),
		),
		migrations.AddField(
			model_name='temporarytoken',
			name='user',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
			                        related_name='ge_temporary_token', to=settings.AUTH_USER_MODEL),
		),
		migrations.AddField(
			model_name='apikey',
			name='user',
			field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
			                           related_name='auth_token', to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterUniqueTogether(
			name='venueviewertype',
			unique_together={('venue', 'name')},
		),
	]
