# Generated by Django 2.2.3 on 2020-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsection',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dashboardsection',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
